[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.124.1" # or another known-good version
  HUGO_EXTENDED = "true"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/submission-created"
  method = "POST"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = ""