backend:
  name: git-gateway
  branch: master 
  repo: vilois/circlelytics-hugo
  base_url: https://wondrous-llama-f95062.netlify.app/admin
media_folder: "static/img"
public_folder: "/img"
collections:  
  - name: "posts_2020"
    label: "Posts / 2020" 
    folder: "content/post/2020"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "Description", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"        
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string", required: false }
          - { label: "Type", name: "type", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }    